### ISSUE TITLE
Setting prefix_key causes ErrorException

### ISSUE THREAD

**Issue by WishCow** [LeaseWeb/LswMemcacheBundle#3]
I have the following config:

``` yaml
lsw_memcache:
    clients:
        general:
            hosts:
                - { dsn: localhost, port: 11211 }
            options:
                prefix_key: lingo_general_

```

This results in:

```
ErrorException: Warning: Memcached::setOption(): error setting memcached option in /srv/http/lingo/vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php line 1087

 in /srv/http/lingo/vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php line 1087
at ErrorHandler->handle('2', 'Memcached::setOption(): error setting memcached option', '/srv/http/lingo/vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php', '1087', array('option' => '15', 'value' => '0', 'start' => '1365523204.4116', 'name' => 'setOption'))
at Memcached->setOption('15', '0') in /srv/http/lingo/vendor/leaseweb/memcache-bundle/Lsw/MemcacheBundle/Cache/LoggingMemcache.php line 1087
at LoggingMemcache->setOption('15', '0') in /srv/http/lingo/app/cache/dev/appDevDebugProjectContainer.php line 2269
at appDevDebugProjectContainer->getMemcache_GeneralService() in /srv/http/lingo/app/bootstrap.php.cache line 211
...
```

If I remove the prefix_key, everything is fine.
