### ISSUE TITLE
Memcache connections are left open after page load

### ISSUE THREAD

**Issue by Dukecz** [LeaseWeb/LswMemcacheBundle#37]
After every page load the memcached Curr Connections is increased and when it hits Max Connection the whole website stop working because of connection timeout.

My `config.yml`:

```yml
lsw_memcache:
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
            prefix: %cache_prefix%
        result_cache:
            client: default
            entity_manager: default          # you may specify multiple entity_managers
            prefix: %cache_prefix%
        query_cache:
            client: default
            entity_manager: default
            prefix: %cache_prefix%
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }
```
