### ISSUE TITLE
Is there a command for clearing cache by client?

### ISSUE THREAD

**Issue by bigfoot90** [LeaseWeb/LswMemcacheBundle#46]
Is there a command for clearing cache by client?

**Comment by mevdschee** [comment]
app/console memcache:clear

**Comment by bigfoot90** [comment]
Suppose you have the following configuration:
```yml
lsw_memcache:
    session:
        client: sessions
        prefix: "session_"
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: doctrine
            entity_manager: [default, read]  # you may specify multiple entity_managers
            prefix: "result_"                # you may specify a prefix for the entries
        query_cache:
            client: doctrine
            entity_manager: default
    clients:
        sessions:
            hosts:
                - { dsn: localhost, port: 11212 }
        doctrine:
                - { dsn: localhost, port: 11212 }
```
I want to clear only the doctrine cache, but your command clears all.
I'm using the command with regex ```app/console memcache:clear  --regex='^(?!session_)'``` as a fallback for now.
But a command like this ```app/console memcache:clear  --client=doctrine``` would be much cleaner.
