### ISSUE TITLE
Session cache dos not work

### ISSUE THREAD

**Issue by manelpm10** [LeaseWeb/LswMemcacheBundle#47]
I've installed and configured LswMemcacheBundle acording with the documentation:

Modified app/AppKernel.php, added the lsw_memcache to the config.yml

```yaml
lsw_memcache:
    session:
        client: sessions
        prefix: "session_"
        ttl: 7200
        locking: true
        spin_lock_wait: 150000
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }
        sessions:
            hosts:
              - { dsn: localhost, port: 11211 }
```

And the memcached server is working as expected

```console
$ telnet localhost 11211
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
quit
Connection closed by foreign host.
```

But the sessions aren't stored in the memcached. I've seen in the known issues that debug doesn't show the memcached hits/writes... for session, but anyway, I've debuged the LockingSessionHandler and is never accessed (even instantiated).

Am I missing something?

Thank you very much for your help.
