### ISSUE TITLE
You have requested a non-existent parameter "memcache.session_handler.auto_load".

### ISSUE THREAD

**Issue by Tanariel** [LeaseWeb/LswMemcacheBundle#52]
Hello,

the documentation states that : 

>This bundle also provides support for storing session data on Memcache servers. To enable session support you will have to enable it through the session key (auto_load is true by default). Note that the only required subkey of the session support is pool (a valid pool). You can also specify a key prefix and a ttl.

But if you *don't want to enable the session* and disable this option you get this error : 

```
ParameterNotFoundException in ParameterBag.php line 106:
You have requested a non-existent parameter "memcache.session_handler.auto_load". Did you mean this: "memcache.session_handler.class"?
```

Here is my configuration in config.yml : 

``` 
lsw_memcache:
    pools:
         default:
           servers:
                - { host: localhost, tcp_port: 11211 }
            options:
                allow_failover: true
                max_failover_attempts: 20
                default_port: 11211
                chunk_size: 32768
                protocol: ascii
                hash_strategy: consistent
                hash_function: crc32
                redundancy: true
                session_redundancy: 2
                compress_threshold: 20000
                lock_timeout: 15
#        sessions:
#            servers:
#                - { host: localhost, tcp_port: 11212 }
#    session:
#        auto_load: false
#        pool: sessions
```

I'm using Symfony version 2.7.1.

Thanks in advance for pointing out any obvious mistake i would have done :)
