### ISSUE TITLE
Add LswMemcache to multiple Doctrine entity manager

### ISSUE THREAD

**Issue by odoucet** [LeaseWeb/LswMemcacheBundle#59]
Documentation already gives information about how to add LswMemcacheBundle support on Doctrine (see https://github.com/LeaseWeb/LswMemcacheBundle#doctrine-support)
But even if this is well handled for default entity manager, it seems it does not work for multiple entity managers : 

When using executeCacheQuery() we get : 
**Trying to cache a query but no result driver is configured.** 

Another way to check : 
```php
dump($this->get('doctrine')->getManager('metrics')->
    getConnection()->getConfiguration()->getResultImpl()); 
// dump NULL
```

Copy of YAML : 
```yml
lsw_memcache:
    pools:
        default:
            servers:
              - { host: 127.0.0.1, tcp_port: 11211 }
    doctrine:
        metadata_cache:
            pool: default
            entity_manager: [default, metrics]
            document_manager: default
        result_cache:
            pool: default
            entity_manager: [default, metrics]
            prefix: "result_"
        query_cache:
            pool: default
            entity_manager: [default, metrics]
```

If we try to add the cache class ourself, we end with an error : 

```php
$cache = $this->get('memcache.default');
$config = $this->get('doctrine')->getManager('metrics')->getConnection()->getConfiguration();
$config->setResultCacheImpl($cache);
```
This gives this error : 
**Argument 1 passed to Doctrine\DBAL\Configuration::setResultCacheImpl() must implement interface Doctrine\Common\Cache\Cache, instance of Lsw\MemcacheBundle\Cache\AntiDogPileMemcache given.**
