### ISSUE TITLE
Sessions doesn't work with the bundle & SF2.2.1

### ISSUE THREAD

**Issue by bartgryszko** [LeaseWeb/LswMemcacheBundle#6]
Hi,

I'm on Symfony 2.2.1& LswMemcacheBundle is installed. I've tried to run sessions handling on two different servers, but after ie. login, nothing happend – session isn't writed down. If I switch back to file-based-sessions everything seems to work.

My config.yml:

```
lsw_memcache:
    session:
        client: sessions
        prefix: "my_session_"
        ttl: 7200
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }
            options:
                prefix_key: "my-dev"
        sessions:
            hosts:
                - { dsn: localhost, port: 11212 }
```
