### ISSUE TITLE
Warning: MemcachePool::set(): The lowest two bytes of the flags array is reserved for pecl/memcache internal use

### ISSUE THREAD

**Issue by Tanariel** [LeaseWeb/LswMemcacheBundle#66]
Hello,

i'm running a server on ubuntu 14.04, with the 3.0.8 memcache extension and i get this : 

An exception has been thrown during the rendering of a template ("Warning: MemcachePool::set(): The lowest two bytes of the flags array is reserved for pecl/memcache internal use")

The only trail i found was here : 
http://stackoverflow.com/questions/3740317/php-memcached-error

but i didn't find a way to solve that at the moment.

Thanks in advance for any help you could provide.

**Comment by mevdschee** [comment]
Can you show the code that calls the "set" method?

**Comment by Tanariel** [comment]
Ok my bad, i only now realised that by changing the extension, the syntax of the set / get have changed.

Will refactor my code according to the new parameters for those functions.

Thanks for the help :)

**Comment by andrzejdziekonski** [comment]
Hi,

i also have this warning. No mather what do i use: set , or setAdp. My declaration is:
for 'set' in controller:
```$this->get('memcache.default')->set($key, $value, 0, 7200);```

for 'setAdp' in controller:
```$this->get('memcache.default')->setAdp($key, $value, 7200);```

I use default bundle configuration: 
```
lsw_memcache:
    doctrine:
        metadata_cache:
            pool: default
            entity_manager: default       
            document_manager: default      
        result_cache:
            pool: default
            entity_manager: [default, read]  
            prefix: "result_"         
        query_cache:
            pool: default
            entity_manager: default
    session:
        pool: sessions
        auto_load: true
        prefix: "session_"
        ttl: 7200
        locking: true
        spin_lock_wait: 150000
    pools:
        default:
            servers:
                - { host: localhost, tcp_port: 11211, weight: 15 }
            options:
                allow_failover: true
                max_failover_attempts: 20
                default_port: 11211
                chunk_size: 32768
                protocol: ascii
                hash_strategy: consistent
                hash_function: crc32
                redundancy: true
                session_redundancy: 2
                compress_threshold: 20000
                lock_timeout: 15
```

Might it be any server memcached configuration problem?
