### ISSUE TITLE
Symfony reporting 2x memory usage

### ISSUE THREAD

**Issue by agemmell** [LeaseWeb/LswMemcacheBundle#7]
Hello!  I am just starting out using Memcached with Doctrine (in Symfony) and I've gone straight to using your bundle to help me do that.

I am testing the Memcached caching on an API call which makes just 4 queries but returns a lot of data.  This data is parsed and output as JSON.  I intend to simply cache those 4 queries.

Straight away I am experiencing something surprising.  Symfony's debug bar is now reporting roughly twice the memory usage (~118MB) than when I am not using Memcached (~55MB).  My question is simply this: is this normal?  I was actually expecting much LESS memory to be reported as being used because the DB wouldn't be hit.  Can anyone explain why it virtually doubled?

I presume the DB memory is being saved (I'm not sure how to measure this?) but why has this led to an increase in PHP memory?

My config is a virtual copy and paste of your default except I don't want to cache my sessions:

```
lsw_memcache:
#    session:
#        client: default
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: default
            entity_manager: default
            prefix: "result_"                # you may specify a prefix for the entries
        query_cache:
            client: default
            entity_manager: default
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }
```

Thank you for any light you can shed on this.
