### ISSUE TITLE
Prefix for pool

### ISSUE THREAD

**Issue by sharipovmarat** [LeaseWeb/LswMemcacheBundle#85]
Hi! 
```
lsw_memcache:
    session:
        pool: default
    pools:
        default:
            servers:
              - { host: 127.0.0.1, tcp_port: 11211 }
            options:
                allow_failover: true
#                prefix_key: "dev_" 
#                prefix_key: "%secret%"
                max_failover_attempts: 20
                default_port: 11211
                chunk_size: 32768
                protocol: ascii
                hash_strategy: consistent
                hash_function: crc32
                redundancy: true
                session_redundancy: 2
                compress_threshold: 20000
                lock_timeout: 15
```

This is my configuration. I have a 2 versions on one server (dev and prod). When i open dev version, memcache data load from prod version. 

Can you add prefix key supporting for this?
